# debugging: dump the whole page source into the feed
# entrySelector = ":root"

[default]
waitUntil = "load"

# see if the basics work
[wikipedia_did_you_know]
title = "Wikipedia — did you know?"
url = "https://en.wikipedia.org/wiki/Main_Page"
waitForSelector = "#mp-dyk > ul li"
entrySelector = "#mp-dyk > ul li"
titleSelector = "b"
linkSelector = "b a"

[exp_view_boom_or_bubble]
title = "AI Boom/Bubble Monitor"
url = "https://boomorbubble.ai/news"
waitForSelector = "tbody tr"
entrySelector = "tbody tr"
titleSelector = ["td:nth-of-type(1)", "td:nth-of-type(4)"]
contentSelector = ["td:nth-of-type(1)", "td:nth-of-type(2)", "td:nth-of-type(3)", "td:nth-of-type(4)"]
linkSelector = "optional:a"

[bitrefill_cz_recently_added_cards]
title = "Bitrefill recently added (CZ)"
url = "https://www.bitrefill.com/cz/en/gift-cards/?s=3"
waitForSelector = "[class*='gridStyles'] a[class*='linkContainer']"
entrySelector = "[class*='gridStyles'] a[class*='linkContainer']"
titleSelector = "h2"
linkSelector = "*"
contentSelector = ["h2", "p[class*='price']"]

[kobo_libra_2_firmware]
title = "Kobo Libra 2 latest firmware"
url = "https://pgaskin.net/KoboStuff/kobofirmware.html"
waitForSelector = "xpath=//*[@id='section-latest']//tbody//tr[.//*[contains(@class,'kfw-latest__hardware') and normalize-space(.)='kobo9']]"
entrySelector = "xpath=//*[@id='section-latest']//tbody//tr[.//*[contains(@class,'kfw-latest__hardware') and normalize-space(.)='kobo9']]"
titleSelector = [".kfw-latest__model", ".kfw-latest__version"]
linkSelector = "a.kfw-latest__links__notes"
contentSelector = [".kfw-latest__model", ".kfw-latest__hardware", ".kfw-latest__version", ".kfw-latest__date"]

[moz_addon_remove_youtube_suggestions]
title = "RYS — Remove YouTube Suggestions versions"
url = "https://addons.mozilla.org/en-US/firefox/addon/remove-youtube-s-suggestions/versions/"
waitForSelector = ".AddonVersionCard"
entrySelector = ".AddonVersionCard"
titleSelector = ".AddonVersionCard-version"
contentSelector = [".AddonVersionCard-fileInfo", ".AddonVersionCard-releaseNotes"]

[tapology_upcoming_events]
title = "Tapology - upcoming events"
url = "https://www.tapology.com/fightcenter?group=major&schedule=upcoming&sport=all"
waitForSelector = "xpath=//*[contains(@class, 'pickDeadlineSidebar')]//tr[.//td]"
entrySelector = "xpath=//*[contains(@class, 'pickDeadlineSidebar')]//tr[.//td]"
titleSelector = ["a", "xpathstr=.//abbr/@title"]
linkSelector = "a"
#dateSelector = "xpathstr=.//abbr/@title"
#dateFormat = "yyyy-MM-dd HH:mm:ss xx"
# this stuff seems to time out with 'load' a lot
waitUntil = "domcontentloaded"

[start_all_back_release_notes]
title = "StartAllBack release notes"
url = "https://www.startallback.com/"
# do not wait here, legacy waitForSelector API requires the element to be visible and it is not by default
#waitForSelector = ".history2"
entrySelector = ".history2"
titleSelector = "xpathstr=./text()[normalize-space()]"
# use the whole element
# contentSelector = "li"

[bellsoft_blog]
title = "The BellSoft Blog"
url = "https://bell-sw.com/blog/"
waitForSelector = "xpath=//*[contains(@class, 'blog_wrapper')]"
entrySelector = "xpath=//*[contains(@class, 'blog_wrapper')]"
titleSelector = "h5"
linkSelector = "a"
contentSelector = "p"

[hacker_news_algolia_top_week]
title = "HN Algolia - top stories (week)"
url = [
  "https://hn.algolia.com/?dateRange=pastWeek&page=0&prefix=false&query=&sort=byPopularity&type=story",
]
waitForSelector = "article.Story"
entrySelector = "article.Story"
titleSelector = ".Story_title span"
linkSelector = ".Story_title a"
# story link is not mandatory, let's just take the whole thing here
# contentSelector = [".Story_link", ".Story_meta"]

[liberation_travel_month_letter]
title = "Liberation Travel Month-letter"
url = "https://liberation.travel/liberation-travel-hacks-month-letter/"
waitForSelector = ".mailpoet_archive li"
entrySelector = ".mailpoet_archive li"
titleSelector = "a"
linkSelector = "a"

[jobstack_it_jobs]
title = "Jobstack.it jobs"
url = "https://www.jobstack.it/it-jobs"
waitForSelector = ".jobposts-list .jobposts-item"
entrySelector = ".jobposts-list .jobposts-item"
titleSelector = ["h3", ".jobposts-item_salary"]
linkSelector = "a"
contentSelector = "xpath=.//*[contains(@class, 'jobposts-item_labels')]/.."

[ceska_kryptomenova_as_blog]
title = "Blog | Česká kryptoměnová asociace"
url = "https://www.ckma.cz/cs/blog"
waitForSelector = "article"
entrySelector = "article"
titleSelector = ".ArticleLink-heading"
linkSelector = "a"

[techpowerup_gpu_reviews]
title = "TechPowerUp.com GPU reviews"
url = "https://www.techpowerup.com/review/?category=Graphics+Cards&manufacturer=&pp=25&order=date"
waitForSelector = "#list"
entrySelector = "#list .reviewlist-bit"
titleSelector = ".title"
linkSelector = ".title a"

[techpowerup_cpu_reviews]
title = "TechPowerUp.com CPU reviews"
url = "https://www.techpowerup.com/review/?category=Processors&manufacturer=&pp=25&order=date"
waitForSelector = "#list"
entrySelector = "#list .reviewlist-bit"
titleSelector = ".title"
linkSelector = ".title a"

[getty_images_ufc_weigh_ins]
title = "Getty images - UFC weigh-ins"
url = "https://www.gettyimages.com/editorial-images/ufc"
waitForSelector = "//article[contains(.//a/@title, 'Weigh') or contains(.//a/@title, 'weigh')]"
entrySelector = "//article[contains(.//a/@title, 'Weigh') or contains(.//a/@title, 'weigh')]"
titleSelector = ["figcaption span", "xpathstr=.//a/@title"]
linkSelector = "a"

[pia_vpn_release_notes]
title = "PIA VPN - release notes"
url = "https://www.privateinternetaccess.com/pages/changelog"
waitForSelector = "article.changelog-release"
entrySelector = "article.changelog-release"
titleSelector = ["h3", "h4"]
linkSelector = "a"

[hacker_news_best_posts_week]
title = "Hacker News - best posts (week)"
url = "https://news.ycombinator.com/best?h=168"
waitForSelector = "tr.submission"
entrySelector = "tr.submission"
titleSelector = ".titleline"
linkSelector = "xpath=following-sibling::tr//a[contains(@href,'item?id=')]"
contentSelector = ["xpath=./*[@class='title'][1]", "xpath=following-sibling::tr", "xpath=./*[@class='title'][2]"]

[notebookcheck_featured_content]
title = "Notebookcheck - featured content"
url = "https://www.notebookcheck.net/"
waitForSelector = ".intro_featured_bar_item"
entrySelector = ".intro_featured_bar_item"
titleSelector = ".intro_featured_bar_title"
linkSelector = "*"
# this stuff seems to time out with 'load' a lot
waitUntil = "domcontentloaded"

[opentrackers_org_posts]
title = "OpenTrackers.org"
url = [
  "https://opentrackers.org/",
  "https://opentrackers.org/page/2/"
]
waitForSelector = ".post-list > .post"
entrySelector = ".post-list > .post"
titleSelector = [".post-date", "h2"]
# linkSelector = "a"

