# debugging: dump the whole page source into the feed
# entrySelector = ":root"

[default]
waitUntil = "load"

# see if the basics work
[wikipedia_did_you_know]
title = "Wikipedia — did you know?"
url = "https://en.wikipedia.org/wiki/Main_Page"
waitForSelector = "#mp-dyk > ul li"
entrySelector = "#mp-dyk > ul li"
titleSelector = "b"
linkSelector = "b a"

[exp_view_boom_or_bubble]
title = "AI Boom/Bubble Monitor"
url = "https://boomorbubble.ai/news"
waitForSelector = "tbody tr"
entrySelector = "tbody tr"
titleSelector = ["td:nth-of-type(1)", "td:nth-of-type(4)"]
contentSelector = ["td:nth-of-type(1)", "td:nth-of-type(2)", "td:nth-of-type(3)", "td:nth-of-type(4)"]
linkSelector = "optional:a"

[bitrefill_cz_recently_added_cards]
title = "Bitrefill recently added (CZ)"
url = "https://www.bitrefill.com/cz/en/gift-cards/?s=3"
waitForSelector = "[class*='gridStyles'] a[class*='linkContainer']"
entrySelector = "[class*='gridStyles'] a[class*='linkContainer']"
titleSelector = "h2"
linkSelector = "*"
contentSelector = ["h2", "p[class*='price']"]

[kobo_libra_2_firmware]
title = "Kobo Libra 2 latest firmware"
url = "https://pgaskin.net/KoboStuff/kobofirmware.html"
waitForSelector = "xpath=//*[@id='section-latest']//tbody//tr[.//*[contains(@class,'kfw-latest__hardware') and normalize-space(.)='kobo9']]"
entrySelector = "xpath=//*[@id='section-latest']//tbody//tr[.//*[contains(@class,'kfw-latest__hardware') and normalize-space(.)='kobo9']]"
titleSelector = [".kfw-latest__model", ".kfw-latest__version"]
linkSelector = "a.kfw-latest__links__notes"
contentSelector = [".kfw-latest__model", ".kfw-latest__hardware", ".kfw-latest__version", ".kfw-latest__date"]

[moz_addon_remove_youtube_suggestions]
title = "RYS — Remove YouTube Suggestions versions"
url = "https://addons.mozilla.org/en-US/firefox/addon/remove-youtube-s-suggestions/versions/"
waitForSelector = ".AddonVersionCard"
entrySelector = ".AddonVersionCard"
titleSelector = ".AddonVersionCard-version"
contentSelector = [".AddonVersionCard-fileInfo", ".AddonVersionCard-releaseNotes"]

[tapology_upcoming_events]
title = "Tapology - upcoming events"
url = "https://www.tapology.com/fightcenter?group=major&schedule=upcoming&sport=all"
waitForSelector = "xpath=//*[contains(@class, 'pickDeadlineSidebar')]//tr[.//td]"
entrySelector = "xpath=//*[contains(@class, 'pickDeadlineSidebar')]//tr[.//td]"
titleSelector = ["a", "xpathstr=.//abbr/@title"]
linkSelector = "a"
#dateSelector = "xpathstr=.//abbr/@title"
#dateFormat = "yyyy-MM-dd HH:mm:ss xx"
# this stuff seems to time out with 'load' a lot
waitUntil = "domcontentloaded"

[start_all_back_release_notes]
title = "StartAllBack release notes"
url = "https://www.startallback.com/"
# do not wait here, legacy waitForSelector API requires the element to be visible and it is not by default
#waitForSelector = ".history2"
entrySelector = ".history2"
titleSelector = "xpathstr=./text()[normalize-space()]"
# use the whole element
# contentSelector = "li"

[bellsoft_blog]
title = "The BellSoft Blog"
url = "https://bell-sw.com/blog/"
waitForSelector = "xpath=//*[contains(@class, 'blog_wrapper')]"
entrySelector = "xpath=//*[contains(@class, 'blog_wrapper')]"
titleSelector = "h5"
linkSelector = "a"
contentSelector = "p"

[hacker_news_algolia_top_week]
title = "HN Algolia - top stories (week)"
url = [
  "https://hn.algolia.com/?dateRange=pastWeek&page=0&prefix=false&query=&sort=byPopularity&type=story",
]
waitForSelector = "article.Story"
entrySelector = "article.Story"
titleSelector = ".Story_title span"
linkSelector = ".Story_title a"
# story link is not mandatory, let's just take the whole thing here
# contentSelector = [".Story_link", ".Story_meta"]

[liberation_travel_month_letter]
title = "Liberation Travel Month-letter"
url = "https://liberation.travel/liberation-travel-hacks-month-letter/"
waitForSelector = ".mailpoet_archive li"
entrySelector = ".mailpoet_archive li"
titleSelector = "a"
linkSelector = "a"

[jobstack_it_jobs]
title = "Jobstack.it jobs"
url = "https://www.jobstack.it/it-jobs"
waitForSelector = ".jobposts-list .jobposts-item"
entrySelector = ".jobposts-list .jobposts-item"
titleSelector = ["h3", ".jobposts-item_salary"]
linkSelector = "a"
contentSelector = "xpath=.//*[contains(@class, 'jobposts-item_labels')]/.."

[ceska_kryptomenova_as_blog]
title = "Blog | Česká kryptoměnová asociace"
url = "https://www.ckma.cz/cs/blog"
waitForSelector = "article"
entrySelector = "article"
titleSelector = ".ArticleLink-heading"
linkSelector = "a"

[getty_images_ufc_weigh_ins]
title = "Getty images - UFC weigh-ins"
url = "https://www.gettyimages.com/editorial-images/ufc"
waitForSelector = "//article[contains(.//a/@title, 'Weigh') or contains(.//a/@title, 'weigh')]"
entrySelector = "//article[contains(.//a/@title, 'Weigh') or contains(.//a/@title, 'weigh')]"
titleSelector = ["figcaption span", "xpathstr=.//a/@title"]
linkSelector = "a"

[pia_vpn_release_notes]
title = "PIA VPN - release notes"
url = "https://www.privateinternetaccess.com/pages/changelog"
waitForSelector = "article.changelog-release"
entrySelector = "article.changelog-release"
titleSelector = ["h3", "h4"]
linkSelector = "a"

[hacker_news_best_posts_week]
title = "Hacker News - best posts (week)"
url = "https://news.ycombinator.com/best?h=168"
waitForSelector = "tr.submission"
entrySelector = "tr.submission"
titleSelector = ".titleline"
linkSelector = "xpath=following-sibling::tr//a[contains(@href,'item?id=')]"
contentSelector = ["xpath=./*[@class='title'][1]", "xpath=following-sibling::tr", "xpath=./*[@class='title'][2]"]

[hacker_news_10_best_posts_week]
title = "Hacker News - 10 best posts (week)"
url = "https://news.ycombinator.com/best?h=168"
waitForSelector = "xpath=(//tr[contains(@class, 'submission')])[position() <= 10]"
entrySelector = "xpath=(//tr[contains(@class, 'submission')])[position() <= 10]"
titleSelector = ".titleline"
linkSelector = "xpath=following-sibling::tr//a[contains(@href,'item?id=')]"
contentSelector = ["xpath=./*[@class='title'][1]", "xpath=following-sibling::tr", "xpath=./*[@class='title'][2]"]

[notebookcheck_featured_content]
title = "Notebookcheck - featured content"
url = "https://www.notebookcheck.net/"
waitForSelector = ".intro_featured_bar_item"
entrySelector = ".intro_featured_bar_item"
titleSelector = ".intro_featured_bar_title"
linkSelector = "*"
# this stuff seems to time out with 'load' a lot
waitUntil = "domcontentloaded"

[opentrackers_org_posts]
title = "OpenTrackers.org"
url = [
  "https://opentrackers.org/",
  "https://opentrackers.org/page/2/"
]
waitForSelector = ".post-list > .post"
entrySelector = ".post-list > .post"
titleSelector = [".post-date", "h2"]
# linkSelector = "a"

[rtings_com_laptop_reviews]
title = "rtings.com - laptop reviews"
url = "https://www.rtings.com/laptop/latest"
waitForSelector = ".latest_page-content .latest_page-preview"
entrySelector = ".latest_page-content .latest_page-preview"
titleSelector = ".latest_page-preview-title"
linkSelector = "*"

[ultrabookreview_com_fanless_ultrabooks]
title = "ultrabookreview - fanless ultrabooks"
url = "https://www.ultrabookreview.com/6520-fanless-ultrabooks/"
waitForSelector = "xpath=//*[@id='content-area']//table[not(.//thead)]//tr[position() > 1]"
entrySelector = "xpath=//*[@id='content-area']//table[not(.//thead)]//tr[position() > 1]"
titleSelector = ["td:nth-of-type(1)", "td:nth-of-type(2)"]
contentSelector = ["td:nth-of-type(1)", "td:nth-of-type(2)", "td:nth-of-type(3)", 
                   "td:nth-of-type(4)", "td:nth-of-type(5)", "td:nth-of-type(6)"]

[notebookcheck_reviews_of_fanless_laptops]
title = "Notebookcheck - reviews of fanless laptops"
url = "https://www.notebookcheck.net/Laptop-Search.8223.0.html?&manufacturer=&model=&lang=2&modelSearchAjax_1=&ajax_getgpu_result_gpu=&ajax_getgpu_gpu=0&gpu_manu=&gpu_architecture=&gpu_class=&modelSearchAjax_2=&ajax_getgpu_result_cpu=&ajax_getgpu_cpu=0&cpu_manu=&exclude_cpu_manu=&cpu_generation=&cpu_cores=&inch=&inch_from=&inch_to=&screen_ratio=&screen_resolution_x=&screen_resolution_y=&screen_glossy=&screen_panel_type=&screen_panel=&screen_refresh_rate=&class=-1&rating=&reviewcount=&dr_workmanship=&dr_display=&dr_emissions=&dr_ergonomy=&dr_performance=&dr_mobility=&dr_temperature=&dr_audio=&dr_camera=&ratingversion=&age=&min_age=&year_from=&year_till=&weight=&size_width=&size_length=&size_depth=&price=&min_price=&min_list_price=&list_price=&ram=&fanless=1&battery_capacity=&battery_capacity_mah=&hdd_size=&hdd_type=&odd_type=&lan_type=&wlan_type=&brightness_center=&de2000_colorchecker=&percent_of_srgb=&percent_of_adobergb=&pwm=&loudness_min=&loudness_cp2077=&loudness_load=&battery_wlan=&os_type=&tag_type=&nbcReviews=1&orderby=0&scatterplot_x=&scatterplot_y=&scatterplot_r="
waitForSelector = "xpath=//table[@id='search']//tr[.//a]"
entrySelector = "xpath=//table[@id='search']//tr[.//a]"
titleSelector = ["td:nth-of-type(1)", "td:nth-of-type(2)", "td:nth-of-type(3) a"]
linkSelector = "a"
contentSelector = "td:nth-of-type(3)"

[privazer_release_notes]
title = "Privazer - release notes"
url = "https://privazer.com/en/changelog.php"
waitForSelector = "xpath=(//*[contains(@class, 'page-header')]//table//p[@class='text1'][normalize-space()])[position() <= 20]"
entrySelector = "xpath=(//*[contains(@class, 'page-header')]//table//p[@class='text1'][normalize-space()])[position() <= 20]"
titleSelector = "strong:nth-of-type(1)"

[csfd_adam_curtis_directed_works]
title = "ČSFD - Adam Curtis - režijní dílo"
url = "https://www.csfd.cz/tvurce/18336-adam-curtis/prehled/"
waitForSelector = "xpath=//div[contains(@class, 'creator-filmography')]//section[.//*[contains(@class, 'box-header') and descendant-or-self::*[contains(normalize-space(.), 'Režisér')]]]//td[@class='name']"
entrySelector = "xpath=//div[contains(@class, 'creator-filmography')]//section[.//*[contains(@class, 'box-header') and descendant-or-self::*[contains(normalize-space(.), 'Režisér')]]]//td[@class='name']"
titleSelector = ["xpath=(./preceding::*[@class='year'][string-length(translate(string(.), '0123456789', '')) < string-length(string(.))])[last()]", "xpath=."]
linkSelector = "optional:a"
contentSelector = []

[apache_subversion_release_history]
title = "Apache Subversion release history"
url = "https://subversion.apache.org/docs/release-notes/release-history.html"
waitForSelector = "#site-content ul li"
entrySelector = "#site-content ul li"
titleSelector = "*"

[python_org_release_history]
title = "Python.org release history"
url = "https://www.python.org/downloads/"
waitForSelector = "xpath=(//*[contains(@class, 'download-list-widget')]//*[contains(@class, 'list-row-container')]//li)[position() <= 35]"
entrySelector = "xpath=(//*[contains(@class, 'download-list-widget')]//*[contains(@class, 'list-row-container')]//li)[position() <= 35]"
titleSelector = [".release-number", ".release-date"]
linkSelector = ".release-enhancements a"
contentSelector = [".release-number", ".release-date", ".release-download", ".release-enhancements"]
