name: Publish RSS feeds to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run 6 times every day
    - cron: '0 1,5,9,12,14,19 * * *'
  workflow_dispatch:

env:
  CI: true
jobs:
  publish-feeds:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble
    steps:
      - name: Setup container environment
        run: |
          mkdir -p /root/.docker
          chmod 755 /root/.docker
          git config --global --add safe.directory $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need history for gh-pages
          persist-credentials: true
      - name: Clone feed-me-up-scotty
        run: |
          git clone --depth 1 https://github.com/std-move/feed-me-up-scotty.git /root/feed-me-up-scotty
      - name: install and compile feed-me-up-scotty
        run: |
          cd /root/feed-me-up-scotty
          npm install
          npm run build   # outputs JS to dist/
      - name: Run feed-me-up-scotty
        env:
          HOME: /root
        run: |
          cd $GITHUB_WORKSPACE
          export DEBUG="info"
          # GitHub Actions unfortunately does not support retries.
          # this is a cumbersome method of retrying twice in case of errors.
          npx /root/feed-me-up-scotty || npx /root/feed-me-up-scotty || npx /root/feed-me-up-scotty
      - name: Deploy to GitHub Pages
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git remote add gh-pages-remote https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git fetch --no-recurse-submodules
          git worktree add ./gh-pages gh-pages
          cd gh-pages
          git rm -r .
          cp -r ../public/. .
          git add .
          git commit --message="Deploying to GitHub Pages from $GITHUB_SHA"
          git push gh-pages-remote gh-pages:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
